version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: apipassword
      MYSQL_DATABASE: api
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "Laravel API"
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      APP_LOCALE: pt_BR
      APP_FALLBACK_LOCALE: pt_BR
      APP_KEY: base64:wC2gNATwukU5IyRFG3SQ3y93dfGGm1SyLwJk0A1kmS8=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: api
      DB_USERNAME: apiuser
      DB_PASSWORD: apipassword
      CACHE_STORE: redis
      REDIS_HOST: redis
      REDIS_CLIENT: predis
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
